name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM
      run: sudo apt-get update && sudo apt-get install -y clang llvm
    - name: Configure
      run: cmake .
    - name: Build
      run: make
    - name: Test Hello
      run: ./strictc examples/hello.strict && clang out.ll src/runtime.c -o prog && ./prog
